# Generated by Django 4.2.3 on 2023-07-04 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta',
            name='banco',
            field=models.CharField(choices=[('NU', 'Nubank'), ('IT', 'Itau'), ('BR', 'Bradesco'), ('ST', 'Santander'), ('CE', 'Caixa econômica')], max_length=2),
        ),
        migrations.AlterField(
            model_name='conta',
            name='tipo',
            field=models.CharField(choices=[('PF', 'Pessoa física'), ('PJ', 'Pessoa jurídica')], max_length=2),
        ),
    ]
